const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  // Real words
  const realWords = [
    "Abenteuer",
    "Aussicht",
    "Buchhaltung",
    "Energieeffizienz",
    "Fahrzeugbestand",
    "Gegendstand",
    "Gesellschaft",
    "Kleinigkeit",
    "Kraftwerk",
    "Landesregierung",
    "Mitarbeiter",
    "Nachhaltigkeit",
    "Produktivität",
    "Schlafzimmer",
    "Sicherheitscode",
    "Sonderangebot",
    "Sprachbarriere",
    "Technologie",
    "Verantwortung",
    "Verfügung",
    "Vermögenswerte",
    "Wachstumsmarkt",
    "Wirtschaftsweise",
    "Zufriedenheit",
    "Zukunftsperspektive",
    "Freiheitsgrad",
    "Erfahrungsbericht",
    "Gesundheitscheck",
    "Leistungskennzahl",
    "Stadtplanung",
    "Verkehrsinfrastruktur",
    "Ausbildungsplatz",
    "Finanzierung",
    "Bauordnung",
    "Kundenservice",
    "Einkommenssteuer",
    "Luftqualität",
    "Technologiefirma",
    "Sicherheitsmaßnahme",
    "Erstklassigkeit",
    "Fremdsprachenkenntnisse",
    "Hochleistungsrechner",
    "Innovationskraft",
    "Langfristigkeit",
    "Nutzungsdauer",
    "Risikomanagement",
    "Sachverständiger",
    "Sicherheitsstrategie",
    "Vertragsabschluss",
    "Wertschöpfung",
    "Wissenschaftler",
    "Zielorientierung",
    "Bildungsweg",
    "Ertragspotential",
    "Forschungsprojekt",
    "Kombinationstool",
    "Lebensqualität",
    "Marktforschung",
    "Personalentwicklung",
    "Rechtsberatung",
    "Ressourcennutzung",
    "Schulungskurs",
    "Technologieplattform",
    "Vertragsbedingungen",
    "Wachstumsstrategie",
    "Zukunftsaussichten",
    "Geschäftsmodell",
    "Innovationspotenzial",
    "Kundenzufriedenheit",
    "Markenentwicklung",
    "Produktinnovationen",
    "Sicherheitskriterien",
    "Wachstumsprognose",
    "Zukunftsvision",
    "Ausbildungsmöglichkeiten",
    "Budgetplanung",
    "Energieeffizienzklasse",
    "Fachkräftemangel",
    "Gesundheitsförderung",
    "Kundenbindung",
    "Lösungsansätze",
    "Marktentwicklung",
    "Nutzerfreundlichkeit",
    "Projektmanagement",
    "Qualitätsmanagement",
    "Risikobewertung",
    "Sicherheitskonzept",
    "Technische Innovation",
    "Vertriebsstrategie",
    "Wachstumschancen",
    "Zielsetzung",
    "Bildungseinrichtung",
    "Energieverbrauch",
    "Fachwissen",
    "Innovationsstrategie",
    "Kundenanfrage",
    "Marktfähigkeit",
    "Prozessoptimierung",
    "Sicherheitsüberprüfung",
    "Technologische",
    "Verhandlungsführung",
    "Wachstumsförderung",
    "Zukunftstrends",
  ];

  // Fake words
  const fakeWords = [
    "Flenzker",
    "Grubwinkel",
    "Zeifendorf",
    "Hortelbach",
    "Waldtreif",
    "Krollsmann",
    "Dranfeld",
    "Zorviker",
    "Tremborg",
    "Volkendor",
    "Lanstberg",
    "Krimler",
    "Vesperhorn",
    "Brendewald",
    "Scherblich",
    "Nerheim",
    "Tarnitz",
    "Frohburg",
    "Zellenberg",
    "Holtfeld",
    "Rindorff",
    "Brunacker",
    "Lutzheim",
    "Wolzenberg",
    "Drakonitz",
    "Spenzler",
    "Hortland",
    "Korsheim",
    "Fendrich",
    "Zederhorst",
    "Raffenstein",
    "Kaltendorf",
    "Wrenbach",
    "Feldorff",
    "Mosenburg",
    "Kranzland",
    "Zachendor",
    "Lindorff",
    "Grunfeld",
    "Dranghof",
    "Freiborn",
    "Strahlburg",
    "Korbinger",
    "Leifenthal",
    "Matzendorf",
    "Gorimberg",
    "Waldheim",
    "Eckhart",
    "Schruftor",
    "Grenheim",
    "Brandel",
    "Trostfeld",
    "Wiesenbach",
    "Franzburg",
    "Lattendorf",
    "Kohlmann",
    "Tarnburg",
    "Helmert",
    "Breitdorf",
    "Zarenbeck",
    "Wilkendorf",
    "Rivendorf",
    "Brassheim",
    "Mullenbach",
    "Lenzendorf",
    "Wittendorf",
    "Freiholt",
    "Ludiger",
    "Wachendorf",
    "Vernwald",
    "Giselbach",
    "Horgenberg",
    "Tiefeld",
    "Gossendorf",
    "Schortland",
    "Kronburg",
    "Lindenwerth",
    "Morgenhof",
    "Kranzorf",
    "Zeichenbach",
    "Vorlander",
    "Brenzwald",
    "Hollendorf",
    "Grunewald",
    "Staufenberg",
    "Waldenburg",
    "Tegenhorn",
    "Brisendorf",
    "Rabenstein",
    "Weidelbach",
    "Korvinus",
    "Marnitz",
    "Sellenbach",
    "Zulrich",
    "Erhart",
    "Grotendorf",
    "Vernitz",
    "Bruderbach",
    "Haldendorf",
    "Kreuzberg",
    "Leifner",
    "Schwenzler",
    "Gersbach",
    "Fenker",
    "Hohenfeld",
    "Zeichenberg",
    "Tromsen",
    "Brandhorst",
    "Waldsheim",
    "Schofer",
    "Kramfeld",
    "Hollermark",
  ];
  

  // Add real words to database
  for (const word of realWords) {
    await prisma.word.create({
      data: { word, isReal: true },
    });
  }

  // Add fake words to database
  for (const word of fakeWords) {
    await prisma.word.create({
      data: { word, isReal: false },
    });
  }
}

main()
  .catch((e) => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
